version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_spring_security
    restart: always
    ports:
      - "5051:5432"  # <--- Host port 5051 maps to container port 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jwt_security
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
